<h1 style='text-align: center'> COMSATS University, Islamabad </h1>
<h1 style='text-align: center'> Department of Computer Science </h1>
<h1 style='text-align: center'> CSC483 - Topics in Computer Science II (Programming for Artificial Intelligence) </h1>
<h2 style='text-align: center'> Quiz 03 </h2>
<h2 style='text-align: center'> Submitted by: Waleed Butt SP18-BCS-170 </h2>

In [1]:
from matplotlib import pyplot as plt
import numpy as np
import numpy.matlib as mb

In [2]:
# Train Samples
x = np.array([[0.5, 0.7, 0.2], [0.4, 0.1, 0.5]])
y = np.array([[0.6, 0.3, 0.4]])

# Weights and Bias
w1 = np.array([[0.2, 0.15], [0.1, 0.2]])
w2 = np.array([[0.3, 0.7]])
j = np.array([[0.5, 0.8]])
b = np.array([[0.2, 0.1]])
m=3

# Normalize with zero mean variation
x = (x - np.mean(x))/np.std(x)

# Learning Rates
lr = 0.5

for i in range(3):
    
    # Inpur to hidden layer 2
    z = w1.dot(x)
    print('\n1. Values of W1 = '+str(w1))
    print('\n2. Values of Z  = '+str(z))
    print('\n3. Values of Z mean = '+str(np.mean(z)))
    print('\n4. Values of Z Variance = '+str(np.var(z)))

    # Normalize with zero mean variation
    z_norm = (z - np.mean(z))/np.std(z)
    print('\n5. Values of Z Normalized = '+str(z_norm))

    # Scaling with j and biasing with b
    z_batch = np.array([j[0][0]*z_norm[0,:] + b[0][0], j[0][1]*z_norm[1,:] + b[0][1]])
    print('\n6. Values of Z Bach Normalized = '+str(z_batch))
    print('\n7. Values of J  = '+str(j))
    print('\n8. Values of B  = '+str(b))
    print('\n9. Values of W2 = '+str(w2))
    
    # Relu Activation
    a1 = np.copy(z_batch)
    a1[a1<0] = 0
    y_hat = w2.dot(a1)
    print('\n10. Values of Yhat  = '+str(y_hat))
    
    cost = np.sum((z - y)**2) / y.size
    print("\nCost After Iteration %i: %f" %(i, cost))

    # Back Propogation
    dJdYhat=-2*(y-y_hat)
    dYdw2=np.conjugate(a1).T
    dJdw2=np.matmul(dJdYhat,dYdw2)
    temp = w2.conj().transpose()
    dYda=np.tile(temp,(1 ,3))
    dadzBatch = np.ones(z_batch.shape)
    dadzBatch[z_batch<0] = 0
    dJdzBatch = (mb.repmat(dJdYhat, w2.shape[1], 1) * dYda * dadzBatch)
    dzBatchdj=z_norm
    dJdj = np.sum(dJdzBatch*dzBatchdj, 1)
    dJdb = np.sum(dJdzBatch*1, 1)
    dzBatchdzNorm = np.tile(j, (1,m))
    temp = np.array([[1/z[0].std(), 1/z[1].std()]])
    dzNormdz = np.tile(temp.T, (1,m))
    dzBatchdzNorm = dzBatchdzNorm.reshape((3, 2))
    dJdz = np.matmul(np.matmul(dJdzBatch, dzBatchdzNorm), dzNormdz)
    dzdw1= x.conj().T
    dzdw1 = x.conj().T
    dJdw1 = np.matmul(dJdz,dzdw1)
    w2=w2-lr*dJdw2
    j=np.array([j[0].T-lr*dJdj])
    b=np.array([b[0]-lr*dJdb])
    w1=w1-lr*dJdw1


1. Values of W1 = [[0.2  0.15]
 [0.1  0.2 ]]

2. Values of Z  = [[ 1.00000000e-01  7.50000000e-02 -1.25000000e-01]
 [ 5.00000000e-02 -1.50000000e-01  6.66133815e-17]]

3. Values of Z mean = -0.008333333333333274

4. Values of Z Variance = 0.009305555555555562

5. Values of Z Normalized = [[ 1.12302895  0.86386843 -1.2094158 ]
 [ 0.6047079  -1.46857632  0.08638684]]

6. Values of Z Bach Normalized = [[ 0.76151448  0.63193421 -0.4047079 ]
 [ 0.58376632 -1.07486106  0.16910947]]

7. Values of J  = [[0.5 0.8]]

8. Values of B  = [[0.2 0.1]]

9. Values of W2 = [[0.3 0.7]]

10. Values of Yhat  = [[0.63709077 0.18958026 0.11837663]]

Cost After Iteration 0: 0.413750

1. Values of W1 = [[ 0.5163238  -0.1663238 ]
 [ 2.56132992 -2.26132992]]

2. Values of Z  = [[ 0.2581619   1.02397139 -0.59948569]
 [ 1.28066496  7.23398975 -3.69199488]]

3. Values of Z mean = 0.9175512375791425

4. Values of Z Variance = 10.67078051111851

5. Values of Z Normalized = [[-0.20185701  0.0325781  -0.46440625]
 [ 0